### ISSUE TITLE
'cordova-acpanalytics@latest' is not in this registry

### ISSUE THREAD

**Issue by CYL0728** [adobe/cordova-acpanalytics#8]
Hi,

When i try install the package, the cms show the error below:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cordova-acpanalytics - Not found
npm ERR! 404
npm ERR! 404  'cordova-acpanalytics@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/cordova-acpanalytics - Not found",
    "detail": "\n 'cordova-acpanalytics@latest' is not in this registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

any solution can solve this issue?

**Comment by spoorthipujariadobe** [comment]
Hi,
We are looking into the issue and will get back when we have an update.

**Comment by spoorthipujariadobe** [comment]
Hi,
Could you please verify that you are using the correct command to add the plugin as mentioned in the docs? `cordova plugin add https://github.com/adobe/cordova-acpanalytics.git`. If the issue still persists, please try uninstalling and reinstalling or updating cordova to the latest version. Let us know if this resolves your issue. Thank you.

**Comment by CYL0728** [comment]
@spoorthipujariadobe  Thank you! it is working now.
